version: 2.1
commands:
  persist-env:
    steps:
      - run: cat ${BASH_ENV} >> /tmp/.env
      - persist_to_workspace:
          root: /tmp
          paths:
            - .env
  attach-env:
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/.env >> ${BASH_ENV}

  check-skip:
    steps:
      - run:
          command: |
            if [[ $SKIP == true ]]
            then
              echo "No .go files or version were modified - skipping release" 
              circleci step halt
            fi

  setup-ssh-key:
    steps:
      - run:
          command: |
            chmod +x build-scripts/setup-ssh-keys.sh
            build-scripts/setup-ssh-keys.sh

  validate-release-version-was-incremented:
    steps:
      - run:
          command: |
            set +o errexit
            SKIP=true
            git diff --name-only HEAD~ HEAD | egrep -q "\.go$" && SKIP=false
            git diff --name-only HEAD~ HEAD | egrep -q "VERSION" && SKIP=false
            git log -1 HEAD --pretty=format:%s 2>/dev/null | egrep -q "force release" && SKIP=false
            echo "export SKIP=$SKIP" | tee -a ${BASH_ENV}
            if [[ "SKIP" == "false" ]]
            then
              .circleci/validate-release.sh
              exit $?
            fi

            exit 0

jobs:
  validate:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - validate-release-version-was-incremented
      - persist-env
  test:
    docker:
      - image: cimg/go:1.24
    steps:
      - attach-env
      - checkout
      - setup-ssh-key
      - run: make testacc
  build:
    docker:
      - image: cimg/go:1.24
    steps:
      - attach-env
      - checkout
      - setup-ssh-key
      - run: make build
  release:
    docker:
      - image: cimg/go:1.24
    steps:
      - attach-env
#      - check-skip
      - checkout
      - setup-ssh-key
      - run:
          name: Set up GPG Environment
          command: |
            set -e
            export CI_GPG_HOME="$(mktemp -d)"
            echo "Setting up temporary GPG home: ${CI_GPG_HOME}"
            trap "echo 'Cleaning up temp GPG home...' && rm -rf \"${CI_GPG_HOME}\"" EXIT
            echo "Importing private GPG key from secret variable..."
            echo "$GPG_PRIVATE_KEY_CONTENT" | gpg --batch --yes --import --homedir "${CI_GPG_HOME}"
            echo "Private GPG key imported into temporary keyring."
            export GNUPGHOME="${CI_GPG_HOME}"
            echo "Exported GNUPGHOME=${GNUPGHOME}"
            export GPG_HOME="${CI_GPG_HOME}"
            echo "Exported GPG_HOME=${GPG_HOME} for Makefile variables."
            if [ -n "$GPG_SIGN_KEY_ID" ]; then
             export GPG_SIGN_KEY="$GPG_SIGN_KEY_ID"
             echo "Exported GPG_SIGN_KEY=${GPG_SIGN_KEY} for Makefile."
            else
              echo "Warning: GPG_SIGN_KEY_ID CI secret not found or empty."
            fi
      - run:
          name: Run Release Build (make all)
          command: |
            set -e
            echo "Starting 'make all' pipeline..."
            echo "$GPG_PASSPHRASE" | make all
#      - run: bash .circleci/github-release.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - validate:
          context: terraform-release
#      - test:
#          context: terraform-acceptance
#          requires:
#            - valijate
#      - build:
#          context: terraform-release
#          filters:
#            branches:
#              ignore: master
#          requires:
#            - test
      - release:
          context: terraform-release
#          filters:
#            branches:
#              only: master
          requires:
#            - test
